backend/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('my-profile/', views.my_profile, name="my-profile"),
    path('edit-profile/', views.edit_profile, name="edit-profile")
]

backend/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static
import accounts.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('login/', accounts.views.user_login, name='login'),
    path('logout/', accounts.views.user_logout, name='logout'),
    path('signup/', accounts.views.user_signup, name='signup'),
    path('shop/', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name="home"),
    path('<product_slug>/detail/', views.product_detail, name="product-detail")
]

backend/accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='profiles', default='profiles/default.png')
    phone_number = models.CharField(max_length=16, unique=True, blank=True, null=True)
    
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} {self.phone_number}'

backend/shared/models.py
from django.db import models

# Create your models here.

backend/shop/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    price = models.IntegerField(default=0)
    stock = models.IntegerField(default=0)
    stock_img = models.ImageField(upload_to='products', default='profiles/default.png')

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='cart', on_delete=models.CASCADE)
    product = models.ManyToManyField('shop.Product', related_name='products', through='shop.CartProduct', blank=True)
    price = models.IntegerField(default=0)

    def __str__(self):
        return f'Carrito de {self.user.first_name} {self.user.last_name}'
    

class CartProduct(models.Model):
    product = models.ForeignKey('shop.Product', related_name='on_carts', on_delete=models.CASCADE)
    cart = models.ForeignKey('shop.Cart', related_name='cart_products', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    description = models.TextField()
    input_text = models.CharField(max_length=250, blank=True, null=True)
    input_image = models.ImageField(upload_to='users_input_images', default='profiles/default.png', blank=True, null=True)

    def __str__(self):
        return self.product.name

backend/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password', 'first_name', 'last_name', 'email')
        widgets = dict(password=forms.PasswordInput)
        help_texts = dict(username=None)

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user = super().save(*args, **kwargs)
        return user


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'phone_number')

backend/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import LoginForm, SignupForm, EditProfileForm
from .models import Profile

from shop.models import Cart


def user_login(request):
    FALLBACK_REDIRECT = reverse('shop:home')

    if request.user.is_authenticated:
        return redirect(FALLBACK_REDIRECT)
    if request.method == 'POST':
        if (form := LoginForm(request.POST)).is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if user := authenticate(request, username=username, password=password):
                login(request, user)
                return redirect(request.GET.get('next', FALLBACK_REDIRECT))
            else:
                form.add_error(None, 'Incorrect username or password.')
    else:
        form = LoginForm()
    return render(
        request,
        'accounts/login.html',
        dict(form=form),
    )


def user_logout(request):
    logout(request)
    return redirect('shop:home')


def user_signup(request):
    if request.method == 'POST':
        if (form := SignupForm(request.POST)).is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            Cart.objects.create(user=user)
            login(request, user)
            return redirect('shop:home')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', dict(form=form))


def my_profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/my_profile.html', {'profile': profile})


def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        if (form := EditProfileForm(request.POST, request.FILES, instance=profile)).is_valid():
            form.save()
            return redirect('shop:home')
    else:
        form = EditProfileForm(instance=profile)
    return render(request, 'shared/form.html', {'form': form})

backend/shared/views.py
from django.shortcuts import render

# Create your views here.

backend/shop/views.py
from django.shortcuts import render

from .models import Product

def home(request):
    products = Product.objects.all()
    return render(request, 'shop/home.html', {'products': products})


def product_detail(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    return render(request, 'shop/product_detail.html', {'product': product})

backend/accounts/templates/accounts/login.html
<form method="post" action="{% url 'login' %}">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Login">
</form>

backend/accounts/templates/accounts/my_profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Hola, {{ user.first_name }}</h1>
    <h1> Num: {{ user.profile.phone_number}}</h1>
    <a href="{% url 'accounts:edit-profile' %}">Editar</a>
{% endblock  %}

backend/accounts/templates/accounts/signup.html
<form method="post" action="{% url 'signup' %}">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Sign up">
</form>

backend/shared/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <title>Te Imaginas Creaciones</title>
</head>
<body data-bs-theme="light">
  {% include "nav.html" %}
  {% block content %}
    
  {% endblock  %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

backend/shared/templates/nav.html
{% load static %}
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <button onclick="changeTheme()" class="btn rounded-fill"><i id="d1-icon" class="bi bi-moon-fill"></i></button>  
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:home' %}">Principal</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <a class="btn btn-danger ms-auto" href="{% url 'logout' %}" role="button">
          <i class="bi bi-box-arrow-in-right"></i> Cerrar Sesión
        </a>
        {% else %}
          <a class="btn btn-primary ms-auto" href="{% url 'login' %}" role="button">
            <i class="bi bi-box-arrow-in-right"></i> Iniciar Sesión
          </a>
        {% endif %}
      </div>
    </div>
  </nav>
  <script src="{% static 'js/script.js' %}"></script>
</body>

backend/shared/templates/shared/form.html
<form method="post" action="{% url 'login' %}">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Guardar">
</form>

backend/shop/templates/shop/home.html
{% extends "base.html" %}

{% block content %}

<h1>Hello World</h1>


{% if user.is_authenticated %}
    <h1>Hola, {{ user.username }}</h1>
    <img src="{{ user.profile.avatar.url }}" style="width: 200px;">
    <a href="{% url 'accounts:my-profile' %}">Mi perfil</a>
    <a href="{% url 'accounts:edit-profile' %}">Editar perfil</a>
{% endif %}

<h1>PRODUCTOS</h1>
{% for product in products %}
    <p>{{ product.name }}</p><a href="{% url 'shop:product-detail' product.slug %}">Detalles</a>
{% endfor %}

{% endblock  %}

backend/shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% block content %}
    <p>{{ product.name }}</p>

<img src="{{ product.stock_img.url }}" style="width: 200px;">
{% endblock  %}